[package]
name = "caproxy"
version = "0.1.0"
authors = ["a3r <arrrght@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
rand = "0.6.5"
futures = "0.1.27"
reqwest = "0.9"
hyper = "0.12"
pretty_env_logger = "0.3"
